version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm ci
  pre_build:
    commands:
      - echo "Creating environment.prod.ts..."
      - |
        cat > src/environments/environment.prod.ts <<EOL
        export const firebaseConfig = {
          apiKey: "${FIREBASE_API_KEY}",
          authDomain: "${FIREBASE_AUTH_DOMAIN}",
          projectId: "${FIREBASE_PROJECT_ID}",
          storageBucket: "${FIREBASE_STORAGE_BUCKET}",
          messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
          appId: "${FIREBASE_APP_ID}",
          measurementId: "${FIREBASE_MEASUREMENT_ID}"
        };

        export const environment = {
          production: true,
          lbUrl: "${LB_URL}"
        };
        EOL
  build:
    commands:
      - echo "Building Angular app..."
      - npm run build -- --configuration production
artifacts:
  files:
    - dist/**/*
